### DISCUSSION TITLE
Can't Center Glyphs with NF

### DISCUSSION THREAD

**Discussion by teowelton** [elkowar/eww#1214] [Q&A]
Hey all!

I was wondering how people use Glyphs in EWW. Are they just Nerd Fonts? As I've been making my own eww setup over the past few days, I've struggled with using Nerd Fonts, because it feels like half of the glyphs aren't actually centered, and can't be fixed by (S)CSS. Do people use an alternative, or am I doing something stupidly wrong?

Thanks

**Comment by UnnaturalTwilight** [comment]
It isn't a full solution but using the "Nerd Font Mono" version of a Nerd Font helps with centering as the mono versions have the icons shrunk to fit.
I use this scss for my icons:
```scss
.icons {
    font-size: 3rem;
    color: $kinda-gray;
    font-family: JetBrainsMono NFM; // JetBrains Mono Nerd Font Mono;
    padding: 15px;
}
```
