### DISCUSSION TITLE
scroll widget, is possible a scrollbar?

### DISCUSSION THREAD

**Discussion by gh0stzk** [elkowar/eww#1297] [Q&A]
Scroll widget can show a scrollbar??

**Comment by hypernova7** [comment]
Try this:

Scrollbar almost similar to gtk4
```css

scrollbar {
  trough {
    padding-left: 30px; /* hack to make the scrollbar expand when the mouse is almost close */
    min-width: 3px;

    slider {
      min-width: 4px;
      border-radius: 999999px;
      transition: all 0.2s cubic-bezier(0.22, 1, 0.36, 1);
      background-color: $blue_gray;
    }
  }

  &:hover trough slider {
    min-width: 8px;
    background-color: $blue_gray;
  }

  button {
    margin-left: 30px; /* hack to make the scrollbar buttons expand when the mouse is almost close */
    min-width: 3px;
    min-height: 6px;
    border-radius: 999999px;
    transition: all 0.2s cubic-bezier(0.22, 1, 0.36, 1);
    background-color: $blue_gray;
    -gtk-icon-source: none;

    &.up {
      margin-bottom: 3px;
    }

    &.down {
      margin-top: 3px;
    }
  }

  &:hover {
    button.up {
      background-color: transparent;
      -gtk-icon-source: -gtk-icontheme("pan-up-symbolic");
    }

    button.down {
      background-color: transparent;
      -gtk-icon-source: -gtk-icontheme("pan-down-symbolic");
    }
  }
}

```
