### DISCUSSION TITLE
linear-gradient + `to top` can't be drawn completely

### DISCUSSION THREAD

**Discussion by TornaxO7** [elkowar/eww#580] [Q&A]
I'm trying to create a little dashboard with a linear-gradient background which should look like this:

<details>

![image](https://user-images.githubusercontent.com/50843046/191541437-394f3ffe-5477-4792-b1b5-29f67b435181.png)

</details>

So the `css` config is as follows:
```css
.dashboard {
    background-image: linear-gradient(45deg, white 0%, #5C3566);

    border-radius: 25px;
    border-style: solid;
    border-width: 7px;
    border-color: #e6e6ff;
}
```

The problem is, that it mostly looks like this:

<details>

![image](https://user-images.githubusercontent.com/50843046/191541551-1809963a-aa51-46d7-b29b-703bf4711729.png)

</details>

which is not what I want.

This issue only appears if the gradient goes to the top or bottom. `to left` and `to right` works fine and `background-color` works as well, but if I set `linear-gradient(to bottom, white, #5c3566)` it will pop up like the second image. Does anyone has the same problems?
