### DISCUSSION TITLE
How to use GTK theme colors in scss?

### DISCUSSION THREAD

**Discussion by the-argus** [elkowar/eww#653] [Q&A]
By default, widget's background color matches my GTK theme. however, I added the following scss:
```scss
window {
    background-color: rgba(0.0, 0.0, 0.0, 0.0);
}
```
This means that the window is nicely transparent, and I can set widgets' background colors to be opaque colors, and give them margins, which results in a floating effect. However, I can only manually set these colors, and then would not change if I changed my gtk theme. Is there some gtk scss with color-defines I could import, or something like that?
