### DISCUSSION TITLE
Subtract from a percentage

### DISCUSSION THREAD

**Discussion by Eclextic** [elkowar/eww#850] [Q&A] [answered]
Is there a way to remove a couple px, say for example 10px from the width?
Something like `:width "100% - 10px"`?

```
(defwindow bar
  :monitor 0
  :geometry (geometry :x "0%"
                      :y "0%"
                      :width "100%"
                      :height "10px"
                      :anchor "top center")
  :exclusive true
  (bar))
```

Thanks to everyone in advance!

# Answer
Thanks to [W-lfchen](https://github.com/W-lfchen), check him out, amazing guy!
This results in a red box randomly changing in size

```scss
(defpoll random :interval "1s"
 :initial 800
 "scripts/getrand 0 800")

(defwindow example
  :monitor 0
  :geometry (geometry
    :x "0%"
    :y "0%"
    :width "100%"
    :height "10px"
    :anchor "top center"
  )
  :exclusive true
  (box
    :style "margin-right: ${random}px; margin-left: ${random}px; background-color:red;"
    ""
  ))
```

Very important! (Some GTK themes might interfere with margins, etc.)

```scss
* {
  all: unset;
}

/* Or define your own class in the .yuck script and unset everything there */ 
```

Bash script:
```bash
#!/bin/sh

# Source: https://stackoverflow.com/a/43537627

low=$1
high=$2
value=$((low + RANDOM % (1 + high - low)))
echo $value
```

**Comment by Eclextic** [comment]
Thing is I want it to be perfectly aligned with my compositor if that is possible.

Honestly I just need an answer of the capability of it!
Worst case scenario, I'll just set the pixels to a constant value...

**Comment by oldwomanjosiah** [comment]
Not to my knowledge, but you could do

```lisp
(defwindow bar
  :monitor 0
  :geometry (geometry :x "0%"
                      :y "0%"
                      :width "100%"
                      :height "10px"
                      :anchor "top center")
  :exclusive true
  (box
    ; with the new css property
    :css "padding-right: 10px"
    ; or without
    :class "bar-insets"
    (bar))
```

with the following in `eww.scss` for the class based solution:

```scss
.bar-insets {
  padding-right: 10px;
}
```

**Reply by Eclextic** [reply]
I will try that later!
But I do remember having tried something like that…
Welp let’s see!

**Reply by Eclextic** [reply]
Sadly both solutions don't seem to work on my end, could this be an incompatibility with Wayland?

**Comment by w-lfchen** [comment]
I don't think there is a really simple way to do this if the anchor is "top center", as that disables the `x` property within the geometry.
Of course, if you have a way to get the width of your monitor, you could use an expression block and subtract 10 there.
However, if you want to not be dependent on that, I do have a workaround you could try:
```
(defwindow bar
  :monitor 0
  :geometry (geometry
    :x "0%"
    :y "0%"
    :width "100%"
    :height "100px"
    :anchor "top center"
  )
  :exclusive true
  (box
    :space-evenly false
    (box ; remove this box if the box in the bar widget already uses hexpand
      :hexpand true
      (bar)
    )
    (box
      :width 10
      :style "background-color: transparent;"
      :hexpand false
    )))
```
This simply creates a transparent box next to your bar, with a width of 10px.
If you set `hexpand` to `true` for the box in your bar widget, you don't need the box containing it.
If your bar window itself (class .bar in the scss) has a background-colour that is not transparent, this won't work. In that case, rename the class and apply it to the box containing the bar widget or within the bar widget itself.
I haven't exhaustively tested this, but it should be a good starting point, I'll gladly help more if needed.

**Reply by Eclextic** [reply]
So I decided to simplify my code further...
I ended up on this:
```
(defwindow example
  :monitor 0
  :geometry (geometry
    :x "0%"
    :y "0%"
    :width "100%"
    :height "100px"
    :anchor "top center"
  )
  :exclusive true
  (box
    :space-evenly false
    (box ; remove this box if the box in the bar widget already uses hexpand
      :hexpand true
      (label :text "Hello World!")
    )
    (box
      :width 10
      :style "background-color: transparent;"
      :hexpand false
    )))

```

Pretty much the same as your answer, but instead of a custom widget (the bar), just a label.

This is what it looks like (Ignore the variable. I tried to create a script to get a random number, to test out if the width would even change, it didn't): 
![image](https://github.com/elkowar/eww/assets/81909104/012da587-cda4-4111-b4e9-2fed37ad34c9)

What do you suggest we do?

**Reply by Eclextic** [reply]
PS: I do have a GTK Theme if that could cause issues...

**Reply by w-lfchen** [reply]
It's your gtk theme.
From my understanding, the example window inherits the class example, which in turn has a background colour set by the theme.
To deal with this, add the following to your eww.scss:
```
.example { // replace example with the name of your window
  background-color: unset;
}
```
and then simply style the label/whatever replaces it with a background colour in your eww.scss file by adding a class to it.

Also, if you want to disable everything from your gtk theme, consider adding
```
* {
  all: unset;
}
```
at the top of you eww.scss file.

**Reply by Eclextic** [reply]
Hmm ok...
So I've tried out what you're suggesting and now understand whats going on...
Your basically just adding a box to one of the sides (right now only the right side has padding, probably fixable by adding another box at the start of the widget).

This solution could work, but is seriously clunky...
Is it possible to define a polled variable and string interpolate it into the width of the window widget?

For example, why does this not display a new value every second (It just shows the initial value):
```scss
(defpoll random :interval "1s"
 :initial "512" 
 "scripts/getrand")

(defwindow example
 :monitor 0
 :geometry (geometry
     :x "0%"
     :y "0%"
     :width "100%"
     :height "10px"
     :anchor "top center"
     )
 :exclusive true
 "${random}")
```

And if I could get that to work, could it be used as a variable for width like this:
```scss
(defwindow example
 :monitor 0
 :geometry (geometry
     :x "0%"
     :y "0%"
     :width "${random}px"
     :height "10px"
     :anchor "top center"
     )
 :exclusive true
 (bar))
```

Because that code gives this error, which I don't understand at all:
```
error: Tried to reference variable `random`, but we cannot access variables here
   ┌─ /home/tangerine-dev/.config/eww/eww.yuck:12:16
   │
12 │      :width "${random}px"
   │                ──────
```
Can variables in general not be used for width or is my syntax wrong? (Couldn't find anything in the docs, other than that this is supposedly the way to do string interpolation)

**Bash script:**
```bash
#!/bin/sh

random 0 1024
```

**Reply by Eclextic** [reply]
Nvm, about the bash script... I just learned that the fish shell seems to have this as a built-in feature...

**Reply by Eclextic** [reply]
Here using a variable as a title works, but the error persists whenever I use the variable on the width parameter...

This one (see above): `error: Tried to reference variable random, but we cannot access variables here`

**Reply by w-lfchen** [reply, marked as answer]
Window sizes have to be fixed as far as I'm concerned.
I have found something new that you might want to try though, it's way less clunky and I honestly don't know why I didn't think of this before:
Unset the window class background by any means.
Then give the box containing your bar stuff the following properties:
```
margin-right: 10px;
margin-left: 10px;
```
Here's an example:
```
(defpoll random :interval "1s" "fish -c \"random 0 1024\"")
(defwindow example
  :monitor 0
  :geometry (geometry
    :x "0%"
    :y "0%"
    :width "100%"
    :height "10px"
    :anchor "top center"
  )
  :exclusive true
  (box
    :style "margin-right: ${random}px; margin-left: ${random}px; background-color:red;"
    "sample text"
  ))
```

On a different note, you can start a script with `#!/bin/fish` or something similar, try the following script:
```
#!/usr/bin/env fish
random 0 1024
```

**Reply by Eclextic** [reply]
Regarding the shell scripts, I already found a solution for bash (I want my scripts to be compatible and as bash is always installed it's preferred).
Solution:
```bash
#!/bin/sh

# Source: https://stackoverflow.com/a/43537627

low=$1
high=$2
value=$((low + RANDOM % (1 + high - low)))
echo $value
```

Seems like bash has a variable/property that generates a random value between 0 and 32768 (unsigned 8 bit value), and we can modulate it to our respective range.


Anyways... Thank you!
It actually now works!

This results in a red bar randomly changing in size
```scss
(defpoll random :interval "1s"
 :initial 800
 "scripts/getrand 0 800")

(defwindow example
  :monitor 0
  :geometry (geometry
    :x "0%"
    :y "0%"
    :width "100%"
    :height "10px"
    :anchor "top center"
  )
  :exclusive true
  (box
    :style "margin-right: ${random}px; margin-left: ${random}px; background-color:red;"
    (bar)
  ))
```

Very important!
```scss
* {
  all: unset;
}

/* Or define your own class in the .yuck script and unset everything there */ 
```


**I noticed that you have some exams coming up! I bet your going to ace them :)
Thank you for your time, man!**
