### DISCUSSION TITLE
Using blend modes in eww

### DISCUSSION THREAD

**Discussion by LunaeSomnia** [elkowar/eww#931] [Q&A]
Hello everyone!

I've been using eww for a while and wanted to implement my own design. I wanted to use the css rule `background-blend-mode` and it seems like it does nothing. I've checked the [GTK Css Properties](https://docs.gtk.org/gtk4/css-properties.html) and it seems to be implemented.

My code looks something like this:
```css
.panel {
  background: #fff;
  background-blend-mode: soft-light;
  border-radius: 4px;
  padding: 4px;
  min-width: 24px;
}
```

It looks like this:
![image](https://github.com/elkowar/eww/assets/77613968/9b2cb53f-5d39-416c-8cb3-99915e796beb)

And should look like this:
![image](https://github.com/elkowar/eww/assets/77613968/2f7f8307-6e47-4194-b424-d243d5995fda)

What am I doing wrong? Does eww not implement it?

Thanks all.
