### DISCUSSION TITLE
Wrong transparent color

### DISCUSSION THREAD

**Discussion by LunaeSomnia** [elkowar/eww#932] [Q&A]
Hello everyone.

I've been experimenting wrong background colors on eww. It appears as if the transparent color was firstly calculated on a black background and then composited on top.

Code: 
```css
.panel {
  background: rgba(#fff, 0.1);
  border-radius: 4px;
  padding: 4px 8px;
  min-width: 24px;
}
```

Result:
![image](https://github.com/elkowar/eww/assets/77613968/ef210beb-fc4e-424e-a28f-1145ac2c455e)

How can I solve this?

Thanks all.
