### DISCUSSION TITLE
Styling Scale Widget

### DISCUSSION THREAD

**Discussion by Mr-EmPee** [elkowar/eww#939] [Q&A] [answered]
Hi guys how can I remove the circle at the end of the highlight?

Current style
```css
.volume trough highlight {
    background-color: rgb(146, 255, 175);
    border: 0;
}

.volume trough {
    background-color: rgba(0, 0, 0, 0.3);
    border: 0;

    padding: 1px;
}
```
![image](https://github.com/elkowar/eww/assets/86979852/308f78de-f502-4b5b-afa4-51378758bfc8)

**Comment by Mr-EmPee** [comment, marked as answer]
The eww inspector helped my find out that it exits the slider object that basically is that circle.
Fixed by using this css
```css
.volume slider {
    background-image: none;
    border: 0;
    box-shadow: none;
}
```
