### ISSUE TITLE
[BUG] Show-truncated in labels and buttons

### ISSUE THREAD

**Issue by gh0stzk** [elkowar/eww#1083]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

In the new version eww 0.6.0 my calendar widget broke showing 3 points instead of the time "08:35" for example.

![Shot-2024-04-22-083934](https://github.com/elkowar/eww/assets/67278339/2a72f6f8-5609-43e9-90ae-70b5d115dd22)

I solved it by adding :show-truncated "false" to labels.

I don't know why it was truncated, it's only 2 digits... anyway...

---

My powermenu widget uses eventbox and a buttons, not labels and is broken, this is how it looks now, 

![Shot-2024-04-22-085947](https://github.com/elkowar/eww/assets/67278339/8bf3cb6e-e233-44be-8687-25be2cb6fc67)

It should show the glyphs for shutdown, restart, etc.

I don't know if this is related to :show-truncated

### Reproducing the issue

My powermenu.yuck

```bash
(defwidget powermenu []
     (box :class "powermenu"
          :orientation "v"
          :space-evenly "false"
          (lock-power-restart)))


(defwidget lock-power-restart []
	(box :class "powermenu"
		 :orientation "v"
		 :spacing 10
    (eventbox :cursor "pointer"
		(button :class "powermenu lock" 
				:onclick "physlock -d"
				:tooltip "Lock session"
				""))
    (eventbox :cursor "pointer"
		(button :class "powermenu exit" 
				:onclick "bspc quit" 
				:tooltip "Logout bspwm"
				""))
    (eventbox :cursor "pointer"
		(button :class "powermenu reboot" 
				:onclick "systemctl reboot"
				:tooltip "Restart"
				""))
    (eventbox :cursor "pointer"
		(button :class "powermenu shutdown" 
				:onclick "systemctl poweroff"
				:tooltip "Shutdown"
				""))     
  )
)

;; Power Menu ;;
(defwindow powermenu
    :geometry (geometry :x "0%"
                        :y "0%"
                        :anchor "center right")
    :wm-ignore false
    (powermenu))
    
```

My powermenu.scss

```css

window>.powermenu {
  margin: 0.5rem;
  background-color: $bg;
}

.powermenu {
  font-family: "Font Awesome 6 Free Solid";
  font-size: 1.5rem;
  padding: 0.3rem;
  border-radius: 0.5rem;

  &.shutdown {
    color: $red;
  }

  &.reboot {
    color: $green;
  }

  &.lock {
    color: $yellow;
  }

  &.exit {
    color: $magenta;
  }

  button {
    background-color: $bg-alt;
    padding: 1.2rem;

    &:hover {
      background-color: lighten($color: $bg-alt, $amount: 4%);
    }
  }
}

```

### Expected behaviour

Power buttons must show a glyphs

### Additional context

Eww log shows nothing.. 

```
 2024-04-22T15:18:37.171Z [0m[32mINFO [0m [0m[1meww::app   [0m > Opening window powermenu as 'powermenu'
 2024-04-22T15:18:37.171Z [0m[32mINFO [0m [0m[1meww::ipc_server[0m > IPC server initialized
```
