### ISSUE TITLE
[BUG] Border transparency doesn't work properly if a background color is set

### ISSUE THREAD

**Issue by Nairou** [elkowar/eww#1106]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

- Setting a semi-transparent window background: Works great, wallpaper is visible.
- Setting a semi-transparent window border, with no window background: Works great, wallpaper is visible through the border.
- Setting a semi-transparent window boder, with a solid window background color: Wrong result, wallpaper is not visible behind the border.

From what I can tell, the window border is drawn on top of the window's background color. This means that setting a transparent window border won't actually appear transparent, as it will just show the window background color behind it.

### Reproducing the issue

``` css
.my-bar {
  background-color: RGBA(32,32,32,1);    // Remove to get border to appear transparent
  padding: 4px;
  border: 4px solid;
  border-color: RGBA(161,221,224,0.25);
  border-radius: 8px;
}
```

### Expected behaviour

Ideally, the rendering of the window background color would not overlap the rendering of the window border, allowing both a solid window and a transparent border.

For a good example of this being done, see the `niri` window manager. Attempting to replicate niri's border transparency is how I found this issue.
