### ISSUE TITLE
How to style the systray menu?

### ISSUE THREAD

**Issue by baracunatana** [elkowar/eww#1161]
Can anyone tell me how to style (with css) the systray menu?

I can style it changing the settings for the `*` class, but that is not an ideal solution. I tried using eww inspector to gather more information, but the menu disapper when I click on anything in the screen, so it can't be selected in the debugger.

**Comment by LurkAndLoiter** [comment]
In your yuck use `(systray :class "DesiredNameHere")` then reference it in css with `.DesiredNamerHere {background-color: red;}`

**Comment by hypernova7** [comment]
```css
menu {
  padding: 5px;
  background-color: $background;
  color: #fff;

  menuitem {
    border-radius: 5px;
    padding: 8px 12px;
  }
  menuitem:hover {
    background-color: $blue;
  }
}
```
