### ISSUE TITLE
styling for system tray

### ISSUE THREAD

**Issue by sagax** [elkowar/eww#1244]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

Examples of styling the context menu for icons in the system tray are needed, please

### Platform and environment

Linux, X11, Xmonad, openSUSE Tumbleweed, X64

**Comment by hypernova7** [comment]
https://github.com/elkowar/eww/issues/1161#issuecomment-2295482424

**Comment by hypernova7** [comment]
Here is something more complete, these styles can be used to add an arrow to the options that are submenus

```scss
menu {
  padding: 5px;
  background-color: $black;
  color: #fff;

  menuitem {
    border-radius: 5px;
    padding: 8px 12px;
    background-color: transparent;
    transition: all .2s ease;

    &:backdrop {
      background-color: $background;
    }
  }

  menuitem arrow {
    min-width: 16px;
    min-height: 16px;

    &:dir(ltr) {
      -gtk-icon-source: -gtk-icontheme('pan-end-symbolic');
      margin-left: 10px;
      margin-right: 0;
    }
  }

  menuitem:hover {
    background-color: $blue;
  }
}
```

**Comment by sagax** [comment]
It's work, thanks.

It would be great to create a page about widget styling and widget parts.

**Comment by kaii-lb** [comment]
what about styling the "hover over app to show app name" popup?

**Comment by hypernova7** [comment]
most complete version with check fields


```scss
menu {
  border-radius: 15px;
  background-color: $surface0;
  border: 2px solid $blue;
  color: #fff;

  separator:not(:last-child) {
    margin: 0 8px;
    min-height: 2px;
    background-color: $surface1;
  }

  menuitem {
    margin: 0px;
    border-radius: 15px;
    background-color: transparent;
    transition: all 0s ease-in;
    padding: 8px;

    &:hover {
      color: $surface1;
      background-color: $text;

      arrow {
        color: $surface1;
      }

      check:checked {
        color: $text;
      }
    }

    arrow {
      min-width: 16px;
      min-height: 16px;

      &:dir(ltr) {
        -gtk-icon-source: -gtk-icontheme("pan-end-symbolic");
        margin-left: 10px;
        margin-right: 20px;
      }
    }

    check:checked {
      padding-left: 7px;
      margin-right: 10px;
      min-width: 20px;
      min-height: 15px;
      background-color: $blue;
      -gtk-icon-source: -gtk-icontheme("dino-tick-symbolic");
      color: $surface1;
    }

    &:backdrop {
      background-color: $mantle;
    }
  }
}
```

<img width="481" height="205" alt="Image" src="https://github.com/user-attachments/assets/2a6baf4f-d609-4061-847b-43bfddac6517" />

**Comment by noahpolimon** [comment]
> most complete version with check fields
> 
> menu {
>   border-radius: 15px;
>   background-color: $surface0;
>   border: 2px solid $blue;
>   color: #fff;
> 
>   separator:not(:last-child) {
>     margin: 0 8px;
>     min-height: 2px;
>     background-color: $surface1;
>   }
> 
>   menuitem {
>     margin: 0px;
>     border-radius: 15px;
>     background-color: transparent;
>     transition: all 0s ease-in;
>     padding: 8px;
> 
>     &:hover {
>       color: $surface1;
>       background-color: $text;
> 
>       arrow {
>         color: $surface1;
>       }
> 
>       check:checked {
>         color: $text;
>       }
>     }
> 
>     arrow {
>       min-width: 16px;
>       min-height: 16px;
> 
>       &:dir(ltr) {
>         -gtk-icon-source: -gtk-icontheme("pan-end-symbolic");
>         margin-left: 10px;
>         margin-right: 20px;
>       }
>     }
> 
>     check:checked {
>       padding-left: 7px;
>       margin-right: 10px;
>       min-width: 20px;
>       min-height: 15px;
>       background-color: $blue;
>       -gtk-icon-source: -gtk-icontheme("dino-tick-symbolic");
>       color: $surface1;
>     }
> 
>     &:backdrop {
>       background-color: $mantle;
>     }
>   }
> }
> 
> <img alt="Image" width="481" height="205" src="https://private-user-images.githubusercontent.com/23711001/510628819-2a6baf4f-d609-4061-847b-43bfddac6517.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjI0MjUzNDQsIm5iZiI6MTc2MjQyNTA0NCwicGF0aCI6Ii8yMzcxMTAwMS81MTA2Mjg4MTktMmE2YmFmNGYtZDYwOS00MDYxLTg0N2ItNDNiZmRkYWM2NTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTA2VDEwMzA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlYWNhMWM2MjBlZTQyYmU2YzY3N2Q4OGMwOWU5ZjIzYzg4YWM3ZmE5N2U1ZjI0OGZmMTY5MzA2Zjc0MjBkMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._3LM2yCYqxhEoL7jrm86TxxgQf1BcHuHgBpHS-SZZxE">

Hi thank you for this! spent a few hours trying to make sense of the GTK CSS doc to find those myself.

There is also styling for radio buttons and disabled items for those who need it:

```scss
menuitem radio {
    &:checked {
        -gtk-icon-source: -gtk-icontheme("radio-checked-symbolic");
    }
    -gtk-icon-source: -gtk-icontheme("radio-symbolic");

}

menuitem:disabled label {
    color: #888;
}
```

<img width="240" height="165" alt="Image" src="https://github.com/user-attachments/assets/65570a03-e106-4190-88b9-6a424cb3ed2e" />

<img width="238" height="96" alt="Image" src="https://github.com/user-attachments/assets/2ad322e1-1715-429d-af85-7942fb39c86c" />
