### ISSUE TITLE
[BUG] slider not showing with styling

### ISSUE THREAD

**Issue by teije9** [elkowar/eww#1309]
### Checklist before submitting an issue

- [x] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [x] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [x] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

![Image](https://github.com/user-attachments/assets/0a601627-c279-421e-900c-0a6c1ecdaa48)

Right top is my scss file, right bottom is my eww config on the left is the menu they make. for some weird reason the scale is invisible. I've tried using the same methods that other people have used to make a scale but they dont work.

### Platform and environment

arch linux, lates version of eww and zen kernel, hyprland.

**Comment by ajrohr2** [comment]
I've had a similar problem. I created a scale completely mimicking the scss in the examples, and the scale just disappears. Attempting to remove the handle of the scale removes the filled in portion as well.

**Comment by LurkAndLoiter** [comment]
[Per GTK.Scale css Docs](https://docs.gtk.org/gtk3/class.Scale.html)
```
scale[.fine-tune][.marks-before][.marks-after]
├── marks.top
│   ├── mark
│   ┊    ├── [label]
│   ┊    ╰── indicator
┊   ┊
│   ╰── mark
├── [value]
├── contents
│   ╰── trough
│       ├── slider
│       ├── [highlight]
│       ╰── [fill]
╰── marks.bottom
    ├── mark
    ┊    ├── indicator
    ┊    ╰── [label]
    ╰── mark
```
try adding these some gtk themes don't have them set to anything so nothing shows up.
```css
trough highlight {
  background-color: rgb(255,0,0);
  border-radius: 4px;
}

scale trough {
  background-color: rgb(0,0,255);
  box-shadow: 0 1px 2px 1px #06060b;
  border-radius: 9px;
  min-height: 8px;
  min-width: 8px;
  margin: 0 0 7px;
}

slider {
  border-radius: 10px;
  background-color: rgb(0,255,0);
  margin: -7px;
}
```
