### ISSUE TITLE
Tooltips!

### ISSUE THREAD

**Issue by Vermoot** [elkowar/eww#359]
Being able to set custom tooltips for widgets would be cool

**Comment by druskus20** [comment]
haha it really would...

**Comment by iSparsh** [comment]
@Vermoot 
https://elkowar.github.io/eww/widgets.html?highlight=tooltip#widget

**Comment by jokeyrhyme** [comment]
I've started using `:tooltip` , but I'm unsure how to style this with GTK CSS ...

Mine show up as white text with no background colour, which is fine expect when the window underneath them is also white (hard to read)

Is there an example of GTK CSS that styles the tooltip?

**Comment by Vermoot** [comment]
I believe the `:tooltip` property is used only to set the content of the tooltip on a widget. However, what's gonna show is just a regular tooltip styled by your current gtk theme, not your eww css file.

Someone correct me if I'm wrong.

**Comment by jokeyrhyme** [comment]
Oh, this is promising...

This setup has tooltips with no background:

```css
* {
  all: unset;
}
.bar {
  background-color: #000000;
}
```

This setup has tooltips with a black background:

```css
* {
  all: unset;
  background-color: #000000;
}
.bar {
}
```

I just wish I knew a more specific selector for tooltips, but this will work for now

**Comment by viandoxdev** [comment]
> I just wish I knew a more specific selector for tooltips, but this will work for now

Well,
```css
tooltip {
  background-color: black;
  /* ... */
}
```
works (tooltip here references all GtkTooltip widgets). Not sure if you can change a specific widget's tooltip tho.
```css
.widget tooltip {/*...*/}
.widget > tooltip {/*...*/}
```
both do not work
