### ISSUE TITLE
[FEATURE] transparency

### ISSUE THREAD

**Issue by godalming123** [elkowar/eww#420]
### Description of the requested feature

Is it possible to have a transparent background for a window/widget

### Proposed configuration syntax

```css
window {
    background: RGBA(10,10,10,0.7)
}
```

### Additional context

I have tried both the above configuration syntax and added to charecters to the end of a hex code for transparency neither working.

**Comment by VuiMuich** [comment]
This worked for me:
```css
.tooltip {
  background-color: rgba(33, 40, 52, 0.55);
}
```
I don't know if it is the caps or the missing semicolon, that breaks the scss syntax. Plus you need to have a compositor, like `picom` iirc.
