### ISSUE TITLE
[FEATURE] Make border-radius work on the image widget

### ISSUE THREAD

**Issue by FlareStormGaming** [elkowar/eww#486]
### Description of the requested feature

Make the border-radius CSS property properly trim the edges off of an image widget. 

### Proposed configuration syntax

```yuck
(defwidget roundedImage [path]
    (image
        :path path
        :class "rounded"
        :image-height 100
        :image-width 100
    )
)
```
```css
image.rounded {
  border-radius: 5px;
}
```
