### ISSUE TITLE
Why doesn't this CSS work?

### ISSUE THREAD

**Issue by buyBread** [elkowar/eww#634]
The expected behavior of the script and styling below is to have a transparent window in which a smaller widget is centered.
```lisp
(defwindow dock 
    :geometry
        (geometry
            :width "100%"
            :height "36px"
            :anchor "bottom center")
    :reserve
        (struts
            :distance "0px" ;; geometry height auto
            :side "bottom")
    (bar))

(defwidget bar []
    (box :class "bar_widgets"
        (left)
        (right)))

(defwidget left []
    "left")

(defwidget right []
   "right")
   ```
```scss
* { all: unset; }

.dock {
    display: flex;
    background-color: rgba(0,0,0,0); // invis
}

.bar {
    background-color: $background;

    width: 90%;
    height: 50%;

    margin: auto;
}
```
The result is:
![image](https://user-images.githubusercontent.com/32032674/204421960-15ee11c8-eacd-4f91-84b5-516a21e5afae.png)
Instead of the whole bar window being transparent it is the default GTK theme color. This apparently is caused by setting styling in `.bar`, but if I manually set the color in the inspector it applies it (not the sizing and margin part though?). This is pretty basic CSS so I'm fairly confused as to why it doesn't work.
