### ISSUE TITLE
[BUG] Gtk Window exceeded monitor width

### ISSUE THREAD

**Issue by LamprosPitsillos** [elkowar/eww#925]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

![2023-09-23_09-27-41_wind](https://github.com/elkowar/eww/assets/61395246/1a0eb347-1547-44b8-b4d7-d913147069f7)
![2023-09-23_09-28-28_full](https://github.com/elkowar/eww/assets/61395246/ec230243-abb1-4f35-be50-b7296c704fa8)
![2023-09-23_09-30-03_gtk](https://github.com/elkowar/eww/assets/61395246/83b340e4-bfd5-47a0-a9f5-34c2abac783e)

### Reproducing the issue

```lisp
(defwidget smooth_bar []
(box  :space-evenly true :style "border :5px solid red ;"
        :halign "center"
        :orientation "h"
    (box :orientation "h" :class "smooth-border left" )
    (bar)
    (box :orientation "h" :class "smooth-border right" )

    ))

(defwidget bar []
(box 
        :orientation "h"
        :class "eww_bar"

    (lhs)
    (rhs)
    )
)

(defwindow bar
    :monitor 0
    :geometry (geometry 
        :x "0%"
        :y "0%"
        :width "100%"
        :height "0%"
        :anchor "top center")
    :exclusive true
    :namespace "eww"
(smooth_bar) )



```

```scss
.smooth-border{
    min-width :1rem ;
    background-color: transparent;
    border-radius: 20px 15px 0px 0px;
    box-shadow: $background 0px -15px; 
    &.left {

        border-radius: 20px 15px 0px 0px;
    }
    &.right {

        border-radius: 15px 20px 0px 0px ;
    }

} 
.eww_bar{
  background-color: $background;
  padding: 0 2rem;
  border-bottom-right-radius: 10px ;
  border-bottom-left-radius: 10px ;
  min-width: 80rem ; // Removing this doesnt solve the issue
}


```

### Expected behaviour

The gtk window to not go over the monitor border and stop at the edges
