### ISSUE TITLE
[Help] How to add thumb to the Scale widget

### ISSUE THREAD

**Issue by dipanshparmar** [elkowar/eww#989]
I'm sorry. Probably not the right place to ask for this. But I couldn't find any solution anywhere.

I'm using the Scale widget to show a slider, but when I'm setting the property

```css
* {
    all: unset;
}
```
the slider is no longer having the thumb. So how can I add the thumb again (what elements to select in css?). This is kind of what I want:
![image](https://github.com/elkowar/eww/assets/49204837/c22e2b8b-32dd-4f6b-a632-02e7e218a9be)
But I want custom styling for the thumb here.

**Comment by MicrogamerCz** [comment]
I also can't find any solution

> ```
> .scale trough slider{
>   /*css here*/
> }
> ```
> 
> You can find this information by running `eww inspector` in the terminal

It doesn't work. No matter what I change, nothing happens. Min-width, border, background, background-image, color. Nothing.

**Comment by newor0599** [comment]
After tweaking around, i got it working.
```css
.scale trough slider{
  background-image: none;
  background-color: #aa3434;
  border: none;
  padding: 0;
}
```
